name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Build
        run: |
          export WITH_OPENSSL=1
          export CPATH="$CPATH:/usr/local/opt/openssl/include"
          export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/opt/openssl/lib"
          make -f macos.mk

      - name: Prepare output
        run: |
          mv libuwebsockets.a libuwebsockets-macos12.a
          pushd capi
          zip -r ../include.zip *.h
          popd

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos12
          path: |
            include.zip
            libuwebsockets-macos12.a
            LICENSE

  build-macos-arm64:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Build
        run: |
          export WITH_OPENSSL=1
          export CPATH="$CPATH:/opt/homebrew/opt/openssl@3/include"
          export LIBRARY_PATH="$LIBRARY_PATH:/opt/homebrew/opt/openssl@3/lib"
          make -f macos.mk

      - name: Prepare output
        run: mv libuwebsockets.a libuwebsockets-macos-arm64.a

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos-arm64
          path: |
            libuwebsockets-macos-arm64.a

  build-linux:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Get RPi toolchain
        run: |
          wget https://github.com/sfjohnson/rpi-toolchain/releases/download/v0.1.6/aarch64-rpi4-linux-gnu.tar.xz
          tar xf aarch64-rpi4-linux-gnu.tar.xz -C ~

      # rpi: no zlib, no OpenSSL
      # android30: zlib, no OpenSSL
      # linux-x64: zlib and OpenSSL
      - name: Build
        run: |
          make -f rpi-arm64.mk
          make -f rpi-arm64.mk clean
          WITH_OPENSSL=1 make -f linux-x64.mk

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-linux
          path: |
            libuwebsockets-rpi-arm64.a
            libuwebsockets-linux-x64.a

  create-release:
    runs-on: ubuntu-22.04
    needs: [build-macos, build-macos-arm64, build-linux]
    steps:
      - name: Get build output macos12
        uses: actions/download-artifact@v4
        with:
          name: build-output-macos12

      - name:  Get build output linux
        uses: actions/download-artifact@v4
        with:
          name: build-output-linux

      - name: Get build output macos-arm64
        uses: actions/download-artifact@v4
        with:
          name: build-output-macos-arm64

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            include.zip
            libuwebsockets-macos12.a
            libuwebsockets-macos-arm64.a
            libuwebsockets-rpi-arm64.a
            libuwebsockets-linux-x64.a
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
