name: Build Release

on: push

jobs:
  build-macos:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: recursive

      - name: Build
        run: |
          export WITH_OPENSSL=1
          export CPATH="$CPATH:/usr/local/opt/openssl/include"
          export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/opt/openssl/lib"
          make -f macos10.mk
          ls

  build-android:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: recursive

      # Build without OpenSSL
      - name: Build
        run: |
          make -f android30.mk
          ls
