name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive

      - name: Build
        run: |
          export WITH_OPENSSL=1
          export CPATH="$CPATH:/usr/local/opt/openssl/include"
          export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/opt/openssl/lib"
          make -f macos.mk

      - name: Prepare output
        run: |
          mv libuwebsockets.a libuwebsockets-macos11.a
          pushd capi
          zip -r ../include.zip *.h
          popd

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-macos11
          path: |
            include.zip
            libuwebsockets-macos11.a
            LICENSE

  build-macos-arm64:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive

      - name: Build
        run: |
          export WITH_HOMEBREW_LLVM=1
          export WITH_OPENSSL=1
          export CPATH="$CPATH:/opt/homebrew/opt/openssl@3/include"
          export LIBRARY_PATH="$LIBRARY_PATH:/opt/homebrew/opt/openssl@3/lib"
          make -f macos.mk

      - name: Prepare output
        run: mv libuwebsockets.a libuwebsockets-macos-arm64.a

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-macos-arm64
          path: |
            libuwebsockets-macos-arm64.a

  build-android-and-rpi:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive

      - name: Get RPi toolchain
        run: |
          wget https://github.com/sfjohnson/rpi-toolchain/releases/download/v0.0.6/arm-rpi-linux-gnueabihf.tar.xz
          tar xf arm-rpi-linux-gnueabihf.tar.xz -C ~

      # Build both without OpenSSL and RPi without zlib
      - name: Build
        run: |
          make -f android30.mk
          make -f android30.mk clean
          make -f rpi.mk

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-android30-and-rpi
          path: |
            libuwebsockets-android30.a
            libuwebsockets-rpi.a

  create-release:
    runs-on: ubuntu-22.04
    needs: [build-macos, build-android-and-rpi, build-macos-arm64]
    steps:
      - name: Get build output macos11
        uses: actions/download-artifact@v2
        with:
          name: build-output-macos11

      - name:  Get build output android30 and rpi
        uses: actions/download-artifact@v2
        with:
          name: build-output-android30-and-rpi

      - name: Get build output macos-arm64
        uses: actions/download-artifact@v2
        with:
          name: build-output-macos-arm64

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            include.zip
            libuwebsockets-macos11.a
            libuwebsockets-macos-arm64.a
            libuwebsockets-android30.a
            libuwebsockets-rpi.a
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
