name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Build
        run: |
          export WITH_OPENSSL=1
          export CPATH="$CPATH:/usr/local/opt/openssl/include"
          export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/opt/openssl/lib"
          make -f macos.mk

      - name: Prepare output
        run: |
          mv libuwebsockets.a libuwebsockets-macos11.a
          pushd capi
          zip -r ../include.zip *.h
          popd

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos11
          path: |
            include.zip
            libuwebsockets-macos11.a
            LICENSE

  build-macos-arm64:
    runs-on: flyci-macos-large-latest-m2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Build
        run: |
          export WITH_HOMEBREW_LLVM=1
          export WITH_OPENSSL=1
          export CPATH="$CPATH:/opt/homebrew/opt/openssl@3/include"
          export LIBRARY_PATH="$LIBRARY_PATH:/opt/homebrew/opt/openssl@3/lib"
          make -f macos.mk

      - name: Prepare output
        run: mv libuwebsockets.a libuwebsockets-macos-arm64.a

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos-arm64
          path: |
            libuwebsockets-macos-arm64.a

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Get RPi toolchain
        run: |
          wget https://github.com/sfjohnson/rpi-toolchain/releases/download/v0.0.6/arm-rpi-linux-gnueabihf.tar.xz
          tar xf arm-rpi-linux-gnueabihf.tar.xz -C ~

      # rpi: no zlib, no OpenSSL
      # android30: zlib, no OpenSSL
      # linux-x64: zlib and OpenSSL
      - name: Build
        run: |
          make -f android30.mk
          make -f android30.mk clean
          make -f rpi.mk
          make -f rpi.mk clean
          WITH_OPENSSL=1 make -f linux-x64.mk

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-linux
          path: |
            libuwebsockets-android30.a
            libuwebsockets-rpi.a
            libuwebsockets-linux-x64.a

  build-nx:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install devkitPro
        run: |
          sudo mkdir -p /usr/local/share/keyring/
          sudo wget -O /usr/local/share/keyring/devkitpro-pub.gpg https://apt.devkitpro.org/devkitpro-pub.gpg
          sudo add-apt-repository "deb [signed-by=/usr/local/share/keyring/devkitpro-pub.gpg] https://apt.devkitpro.org stable main"
          sudo apt-get update
          sudo apt-get install devkitpro-pacman
          sudo dkp-pacman -S switch-dev
          # find install dir
          # export DEVKITPRO=$(dkp-pacman -Qql pacman | grep "devkitpro/$")
          echo $DEVKITPRO

  create-release:
    runs-on: ubuntu-22.04
    needs: [build-macos, build-macos-arm64, build-linux, build-nx]
    steps:
      - name: Get build output macos11
        uses: actions/download-artifact@v4
        with:
          name: build-output-macos11

      - name:  Get build output linux
        uses: actions/download-artifact@v4
        with:
          name: build-output-linux

      - name: Get build output macos-arm64
        uses: actions/download-artifact@v4
        with:
          name: build-output-macos-arm64

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            include.zip
            libuwebsockets-macos11.a
            libuwebsockets-macos-arm64.a
            libuwebsockets-android30.a
            libuwebsockets-rpi.a
            libuwebsockets-linux-x64.a
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
