name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive

      - name: Build
        run: |
          export WITH_OPENSSL=1
          export CPATH="$CPATH:/usr/local/opt/openssl/include"
          export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/opt/openssl/lib"
          make -f macos.mk

      - name: Prepare output
        run: |
          mv libuwebsockets.a libuwebsockets-macos11.a
          pushd capi
          zip -r ../include.zip *.h
          popd

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-macos11
          path: |
            include.zip
            libuwebsockets-macos11.a
            LICENSE

  build-macos-arm64:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive

      - name: Build
        run: |
          export WITH_HOMEBREW_LLVM=1
          export WITH_OPENSSL=1
          export CPATH="$CPATH:/opt/homebrew/opt/openssl@3/include"
          export LIBRARY_PATH="$LIBRARY_PATH:/opt/homebrew/opt/openssl@3/lib"
          make -f macos.mk

      - name: Prepare output
        run: mv libuwebsockets.a libuwebsockets-macos-arm64.a

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-macos-arm64
          path: |
            libuwebsockets-macos-arm64.a

  build-android:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive

      # Build without OpenSSL
      - name: Build
        run: make -f android30.mk

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-android30
          path: libuwebsockets-android30.a

  create-release:
    runs-on: ubuntu-20.04
    needs: [build-macos, build-android, build-macos-arm64]
    steps:
      - name: Get build output macos11
        uses: actions/download-artifact@v2
        with:
          name: build-output-macos11

      - name: Get build output android30
        uses: actions/download-artifact@v2
        with:
          name: build-output-android30

      - name: Get build output macos-arm64
        uses: actions/download-artifact@v2
        with:
          name: build-output-macos-arm64

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            include.zip
            libuwebsockets-macos11.a
            libuwebsockets-macos-arm64.a
            libuwebsockets-android30.a
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
